version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=suitecrm
      - MYSQL_USER=suitecrm
      - MYSQL_PASSWORD=suitecrm
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - suitecrm

  suitecrm:
    image: webdevops/php-apache:7.4
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - '.:/app'
    depends_on:
      - mysql
    networks:
      - suitecrm

volumes:
  mysql_data:
    driver: local

networks:
  suitecrm:
    driver: bridge 